import type { Script } from '../types';

/** Guion de FarmStock. Orden de escenas: inventario -> qr -> prestamo -> pdf -> offline.
 *  Cada escena fija su propia pantalla y deja la réplica limpia (cierra modales, devuelve lo prestado). */
export const farmScript: Script = [
  {
    id: 'inventario',
    label: { es: 'Todo el inventario, a la vista', en: 'The whole inventory at a glance' },
    steps: [
      { t: 'screen', id: 'inventario' },
      { t: 'wait', ms: 400 },
      { t: 'highlight', to: 'tabla-inventario', ms: 900 },
      { t: 'wait', ms: 300 },
      { t: 'click', to: 'tool-4' },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: 'detalle', ms: 700 },
      { t: 'wait', ms: 400 },
      { t: 'click', to: 'detalle-close' },
      { t: 'wait', ms: 250 },
    ],
  },
  {
    id: 'qr',
    label: { es: 'Un QR por unidad', en: 'One QR per unit' },
    steps: [
      { t: 'screen', id: 'inventario' },
      { t: 'wait', ms: 250 },
      { t: 'click', to: 'tool-4' },
      { t: 'wait', ms: 500 },
      { t: 'click', to: 'gen-qr-MOTO-001' },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: ['qr-svg', 'qr-file'], ms: 900 },
      { t: 'wait', ms: 500 },
      { t: 'click', to: 'qr-close' },
      { t: 'wait', ms: 300 },
      { t: 'click', to: 'detalle-close' },
      { t: 'wait', ms: 250 },
    ],
  },
  {
    id: 'prestamo',
    label: { es: 'Préstamo en segundos', en: 'A loan in seconds' },
    steps: [
      { t: 'screen', id: 'salida' },
      { t: 'wait', ms: 400 },
      { t: 'click', to: 'open-registrar' },
      { t: 'wait', ms: 400 },
      { t: 'select', to: 'loan-aprendiz', value: '1090000103' },
      { t: 'wait', ms: 400 },
      { t: 'type', to: 'loan-codigo', text: 'PALA-002', cps: 10 },
      { t: 'wait', ms: 450 },
      { t: 'click', to: 'loan-confirm' },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: '[data-demo="tabla-prestamos"] tbody tr:first-child', ms: 900 },
      { t: 'wait', ms: 500 },
      { t: 'click', to: 'devolver-PALA-002' },
      { t: 'wait', ms: 400 },
    ],
  },
  {
    id: 'pdf',
    label: { es: 'Reportes en PDF', en: 'PDF reports' },
    steps: [
      { t: 'wait', ms: 250 },
      { t: 'click', to: 'export-pdf' },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: 'pdf-sheet', ms: 900 },
      { t: 'wait', ms: 500 },
      { t: 'click', to: 'pdf-download' },
      { t: 'wait', ms: 600 },
      { t: 'click', to: 'pdf-close' },
      { t: 'wait', ms: 250 },
    ],
  },
  {
    id: 'offline',
    label: { es: 'Sigue funcionando sin internet', en: 'Keeps working offline' },
    steps: [
      { t: 'screen', id: 'salida' },
      { t: 'wait', ms: 350 },
      { t: 'click', to: 'toggle-conn' },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: 'sync-status', ms: 800 },
      { t: 'click', to: 'open-registrar' },
      { t: 'wait', ms: 400 },
      { t: 'select', to: 'loan-aprendiz', value: '1090000106' },
      { t: 'wait', ms: 350 },
      { t: 'type', to: 'loan-codigo', text: 'RAST-002', cps: 10 },
      { t: 'wait', ms: 400 },
      { t: 'click', to: 'loan-confirm' },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: ['pend-badge', 'pending-count'], ms: 1000 },
      { t: 'wait', ms: 500 },
      { t: 'click', to: 'toggle-conn' },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: 'sync-progress', ms: 900 },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: 'sync-done', ms: 800 },
      { t: 'wait', ms: 600 },
      { t: 'click', to: 'devolver-RAST-002' },
      { t: 'wait', ms: 400 },
    ],
  },
];
