import type { Script } from '../types';

/** Guion de la réplica web de GEA. Estado asumido: se parte de la pantalla de acceso (startScreen='login') y las
 *  escenas se ejecutan en orden. Cada `to` es un data-demo real de GeaWebReplica. */
export const geaWebScript: Script = [
  {
    id: 'login',
    label: { es: 'Acceso por rol', en: 'Role-based sign-in' },
    steps: [
      { t: 'wait', ms: 400 },
      { t: 'type', to: 'login-email', text: 'admin@gea-demo.test', cps: 26 },
      { t: 'wait', ms: 250 },
      { t: 'type', to: 'login-password', text: 'demo-gea-2026', cps: 24 },
      { t: 'wait', ms: 350 },
      { t: 'highlight', to: 'login-submit', ms: 600 },
      { t: 'click', to: 'login-submit' },
      { t: 'wait', ms: 900 },
    ],
  },
  {
    id: 'panel',
    label: { es: 'El panel de un vistazo', en: 'The dashboard at a glance' },
    steps: [
      { t: 'screen', id: 'calendario' },
      { t: 'wait', ms: 400 },
      { t: 'highlight', to: 'cal-grid', ms: 900 },
      { t: 'wait', ms: 300 },
      { t: 'move', to: 'upcoming-list', ms: 700 },
      { t: 'highlight', to: 'upcoming-list', ms: 900 },
      { t: 'wait', ms: 300 },
      { t: 'highlight', to: 'upcoming-count', ms: 900 },
      { t: 'wait', ms: 500 },
    ],
  },
  {
    id: 'eventos',
    label: { es: 'Un evento en segundos', en: 'An event in seconds' },
    steps: [
      { t: 'screen', id: 'eventos' },
      { t: 'wait', ms: 400 },
      { t: 'click', to: 'nuevo-evento' },
      { t: 'type', to: 'ev-titulo', text: 'Foro de Innovación Docente', cps: 26 },
      { t: 'type', to: 'ev-desc', text: 'Jornada de buenas prácticas en enseñanza activa para docentes.', cps: 40 },
      { t: 'select', to: 'ev-categoria', value: 'Cultural' },
      { t: 'scroll', to: 'ev-modal-body', by: 380, ms: 500 },
      { t: 'select', to: 'ev-lugar', value: 'Auditorio Principal' },
      { t: 'click', to: 'siapac-ok' },
      { t: 'type', to: 'ev-fecha', text: '2026-10-20', cps: 12 },
      { t: 'select', to: 'ev-ini-h', value: '09' },
      { t: 'select', to: 'ev-fin-h', value: '11' },
      { t: 'scroll', to: 'ev-modal-body', by: 1400, ms: 600 },
      { t: 'click', to: 'ev-enviar' },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: 'evento-row-134', ms: 1100 },
    ],
  },
  {
    id: 'anuncios',
    label: { es: 'Moderación en un clic', en: 'Moderation in one click' },
    steps: [
      { t: 'screen', id: 'anuncios' },
      { t: 'wait', ms: 450 },
      { t: 'highlight', to: 'anuncio-estado-41', ms: 700 },
      { t: 'click', to: 'anuncio-row-41' },
      { t: 'wait', ms: 450 },
      { t: 'highlight', to: 'annd-status', ms: 700 },
      { t: 'click', to: 'annd-aprobar' },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: 'anuncio-estado-41', ms: 1100 },
    ],
  },
  {
    id: 'calendario',
    label: { es: 'Calendario de espacios', en: 'Spaces calendar' },
    steps: [
      { t: 'screen', id: 'calendario' },
      { t: 'wait', ms: 450 },
      { t: 'click', to: 'cal-day-2026-10-13' },
      { t: 'wait', ms: 500 },
      { t: 'highlight', to: 'day-time-125', ms: 900 },
      { t: 'highlight', to: 'day-place-125', ms: 900 },
      { t: 'wait', ms: 400 },
      { t: 'click', to: 'day-modal-close' },
      { t: 'wait', ms: 300 },
    ],
  },
  {
    id: 'usuarios',
    label: { es: 'Roles y permisos', en: 'Roles and permissions' },
    steps: [
      { t: 'screen', id: 'usuarios' },
      { t: 'wait', ms: 450 },
      { t: 'click', to: 'user-ver-4' },
      { t: 'wait', ms: 400 },
      { t: 'click', to: 'drawer-modificar' },
      { t: 'wait', ms: 350 },
      { t: 'select', to: 'drawer-rol', value: '2' },
      { t: 'wait', ms: 400 },
      { t: 'click', to: 'drawer-guardar' },
      { t: 'wait', ms: 600 },
      { t: 'highlight', to: 'user-card-4', ms: 1100 },
    ],
  },
];
